name=Ultra1602Ultimate
version=2.0.0
author=Moaaz Yahia Sherif
maintainer=Moaaz Yahia Sherif
sentence=A high-performance, flicker-free LCD 1602 library with Smart Refresh, Multi-Slot Async Engines, and precise progress bars.
paragraph=This library optimizes LCD1602 performance by using a shadow buffer to refresh only changed characters, eliminating annoying screen flicker. It introduces multi-slot non-blocking engines for concurrent background text effects (Marquee, Blink, Fade, Menus) in both Native 4-bit and I2C modes. Includes auto-centering text and custom system icons without blocking delays.
category=Display
url=https://github.com/moaaz-i/Ultra1602Ultimate
architectures=*
license=MIT
