name=Ultra1602Ultimate
version=1.0.0
author=Moaaz Yahia Sherif
sentence=A high-performance, flicker-free LCD 1602 library with Smart Refresh and built-in precise progress bars.
paragraph=This library optimizes LCD1602 performance by using a shadow buffer to refresh only changed characters, eliminating annoying screen flicker. Supports both Native 4-bit and I2C modes, auto-centering text, and custom icons like battery and signal bars.
category=Display
url=https://github.com/moaaz-i/Ultra1602Ultimate
architectures=*
license=MIT
